export enum AccountStatus {
  PENDING_SIGNATURE = "PENDING_SIGNATURE",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
}

export enum UserRole {
  DIRECTOR = "DIRECTOR",
  TERAPEUTA = "TERAPEUTA",
  ACOMPANIANTE_EXTERNO = "ACOMPANIANTE_EXTERNO",
  COORDINADOR_UNO = "COORDINADOR_UNO",
  COORDINADOR_DOS = "COORDINADOR_DOS",
}

export enum MODALITY_ENUM {
  VIRTUAL = "VIRTUAL",
  PRESENCIAL = "PRESENCIAL",
}

export enum FORMTYPE {
  PLAN_TRABAJO = "PLAN_TRABAJO",
  INFORME_SEMESTRAL = "INFORME_SEMESTRAL",
  INFORME_ADMISION = "INFORME_ADMISION",
  ACTAS = "ACTAS",
  REPORTE_MENSUAL = "REPORTE_MENSUAL",
  SEGUIMIENTO_ACOMPANANTE = "SEGUIMIENTO_ACOMPANIANTE_EXTERNO",
  SEGUIMIENTO_FAMILIA = "SEGUIMIENTO_FAMILIA",
  FACTURA = "FACTURA",
}

export enum DocumentStatus {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum DocumentScope {
  PACIENTE = "PACIENTE",
  ALUMNO = "ALUMNO",
  FAMILIA = "FAMILIA",
}

export enum DocumentType {
  PLAN_TRABAJO = "PLAN_TRABAJO",
  INFORME_SEMESTRAL = "INFORME_SEMESTRAL",
  ACTAS = "ACTAS",
  REPORTE_MENSUAL = "REPORTE_MENSUAL",
  SEGUIMIENTO_ACOMPANANTE = "SEGUIMIENTO_ACOMPANIANTE_EXTERNO",
  SEGUIMIENTO_FAMILIA = "SEGUIMIENTO_FAMILIA",
  FACTURA = "FACTURA",
}
