export enum AccountStatus {
  PENDING_SIGNATURE = "PENDING_SIGNATURE",
  ACTIVE = "ACTIVE",
  DISABLED = "DISABLED",
}

export enum UserRole {
  DIRECTOR = "DIRECTOR",
  TERAPEUTA = "TERAPEUTA",
  ACOMPANIANTE_EXTERNO = "ACOMPANIANTE_EXTERNO",
  COORDINADOR_UNO = "COORDINADOR_UNO",
  COORDINADOR_DOS = "COORDINADOR_DOS",
}

export enum MODALITY_ENUM {
  VIRTUAL = "VIRTUAL",
  PRESENCIAL = "PRESENCIAL",
}

export enum FORMTYPE {
  PLAN_TRABAJO = "PLAN_TRABAJO",
  INFORME_SEMESTRAL = "INFORME_SEMESTRAL",
  INFORME_ADMISION = "INFORME_ADMISION",
  ACTAS = "ACTAS",
  REPORTE_MENSUAL = "REPORTE_MENSUAL",
  SEGUIMIENTO_ACOMPANANTE = "SEGUIMIENTO_ACOMPANIANTE_EXTERNO",
  SEGUIMIENTO_FAMILIA = "SEGUIMIENTO_FAMILIA",
  FACTURA = "FACTURA",
}

export enum DocumentStatus {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ARCHIVED = "ARCHIVED",
}

export enum DocumentScope {
  PACIENTE = "PACIENTE",
  ALUMNO = "ALUMNO",
  FAMILIA = "FAMILIA",
}

export enum DocumentType {
  PLAN_TRABAJO = "PLAN_TRABAJO",
  INFORME_SEMESTRAL = "INFORME_SEMESTRAL",
  ACTAS = "ACTAS",
  REPORTE_MENSUAL = "REPORTE_MENSUAL",
  SEGUIMIENTO_ACOMPANANTE = "SEGUIMIENTO_ACOMPANIANTE_EXTERNO",
  SEGUIMIENTO_FAMILIA = "SEGUIMIENTO_FAMILIA",
  FACTURA = "FACTURA",
}

export enum NotificationType {
  FORM_SUBMITTED = "FORM_SUBMITTED",
  FORM_APPROVED = "FORM_APPROVED",
  FORM_REJECTED = "FORM_REJECTED",
  FORM_EDITED_BY_DIRECTOR = "FORM_EDITED_BY_DIRECTOR",
  FORM_REQUIRES_REVIEW = "FORM_REQUIRES_REVIEW",
}

export enum NotificationStatus {
  UNREAD = "UNREAD",
  READ = "READ",
  ARCHIVED = "ARCHIVED",
}

export enum AuditAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  VERSION_CREATED = "VERSION_CREATED",
  PDF_GENERATED = "PDF_GENERATED",
}
